- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-009bbbd2de3309c55
    zone_id: "Z0063775193GF3RESK5L1"
    domain_name: "dev86.fun"
    #list
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ items }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output       # to capture the output using register keyword  

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"