[mongodb]
mongodb.dev86.fun

[redis]
redis.dev86.fun

[myswl]
mysql.dev86.fun

[rabbitmq]
rabbitmq.dev86.fun

[frontend]
172.31.23.54

[cart]
172.31.27.166

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]     
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Shiva